apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: mysql-db-pv
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-pv-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
