apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mysql-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-mysql-app
  template:
    metadata:
      labels:
        app: node-mysql-app
    spec:
      containers:
        - name: node-mysql-con
          image: divyanshu1994singh/node-app:v3
          ports:
          - containerPort: 3010
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: node-app-config
                key: DB_HOST_NEW
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: node-app-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: node-app-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: node-app-secret
                key: DB_PASSWORD